### ISSUE TITLE
Add sample data in repo?

### ISSUE THREAD

**Issue by patrik-eskelinen** [ivan-usov/FiberApp#9]
Is there a possibility of adding some sample data into the repo to facilitate experimenting with the app? I am looking into evaluating length distributions of SWCNT's with it and it would be interesting to compare the evaluation of different data sources. I think it could be useful for several people looking into using the program.

Br, Patrik

**Comment by ivan-usov** [comment]
Yes, indeed, it would be good to add some real images and data files with coordinates of tracked fibrils. Though, one can already generate some contours with a corresponding image for testing via 'Tools -> Fiber/Image Generator'. Selecting 'Scatter fibers and generate an image' will save both .tif image and .mat data file.  These files can be then loaded in FiberApp with 'Open Image' and 'Open Data' respectively. One can try to refit contours after playing with 'Fiber Tracking Parameters' following with 'Fiber Tracking -> Fit All Fibers', and then run Processing scripts at will.
